version: "3.0"

services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - .:/var/lib/neo4j/import
    environment:
      NEO4J_AUTH: "neo4j/password"
      NEO4J_PLUGINS: '["graph-data-science"]'
